# Generated by Django 6.0.7 on 2026-08-12 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0003_remove_professor_disciplinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('1', '1o Trimestre'), ('2', '2o Trimestre'), ('3', '3o Trimestre')], max_length=1)),
                ('data_aplicacao', models.DateField()),
                ('nota_lancada', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecionacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pct', to='professores.lecionacao')),
            ],
            options={
                'verbose_name': 'PCT',
                'verbose_name_plural': 'PCT',
                'ordering': ['-data_aplicacao', 'trimestre', 'lecionacao'],
                'constraints': [models.UniqueConstraint(fields=('lecionacao', 'trimestre'), name='unique_pct_lecionacao_trimestre')],
            },
        ),
    ]
