# Generated by Django 6.0.7 on 2026-08-16 22:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_initial'),
        ('pct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoPCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_pct', to='alunos.aluno')),
                ('pct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='pct.pct')),
            ],
            options={
                'verbose_name': 'Resultado PCT',
                'verbose_name_plural': 'Resultados PCT',
                'ordering': ['aluno__numero', 'aluno__nome'],
                'constraints': [models.UniqueConstraint(fields=('pct', 'aluno'), name='unique_resultado_pct_aluno')],
            },
        ),
    ]
