# Generated by Django 6.0.7 on 2026-08-17 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0002_resultadopct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadopct',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
