# Generated by Django 6.0.7 on 2026-08-11 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0003_remove_professor_disciplinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControloAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('aula_assistida', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecionacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlos_aulas', to='professores.lecionacao')),
            ],
            options={
                'verbose_name': 'Controlo de Aula',
                'verbose_name_plural': 'Controlo de Aulas',
                'ordering': ['-data', 'lecionacao'],
            },
        ),
    ]
