# Generated by Django 6.0.7 on 2026-08-11 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0003_remove_professor_disciplinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('1', '1o Trimestre'), ('2', '2o Trimestre'), ('3', '3o Trimestre')], max_length=1)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('entregou', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planificacoes', to='professores.professor')),
            ],
            options={
                'verbose_name': 'Planificacao',
                'verbose_name_plural': 'Planificacoes',
                'ordering': ['-data_entrega', 'professor', 'trimestre'],
            },
        ),
    ]
