# Generated by Django 6.0.7 on 2026-08-20 12:39

import django.db.models.deletion
from django.db import migrations, models


def associar_lecionacao_segura(apps, schema_editor):
    Planificacao = apps.get_model('planificacoes', 'Planificacao')
    Lecionacao = apps.get_model('professores', 'Lecionacao')

    for planificacao in Planificacao.objects.exclude(professor_id=None):
        lecionacoes = Lecionacao.objects.filter(professor_id=planificacao.professor_id)
        if lecionacoes.count() == 1:
            planificacao.lecionacao_id = lecionacoes.first().id
            planificacao.save(update_fields=['lecionacao'])


def restaurar_professor(apps, schema_editor):
    Planificacao = apps.get_model('planificacoes', 'Planificacao')

    for planificacao in Planificacao.objects.exclude(lecionacao_id=None):
        planificacao.professor_id = planificacao.lecionacao.professor_id
        planificacao.save(update_fields=['professor'])


class Migration(migrations.Migration):

    dependencies = [
        ('planificacoes', '0001_initial'),
        ('professores', '0003_remove_professor_disciplinas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacao',
            options={'ordering': ['-data_entrega', 'lecionacao__professor', 'trimestre'], 'verbose_name': 'Planificacao', 'verbose_name_plural': 'Planificacoes'},
        ),
        migrations.AddField(
            model_name='planificacao',
            name='lecionacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planificacoes', to='professores.lecionacao'),
        ),
        migrations.RunPython(associar_lecionacao_segura, restaurar_professor),
        migrations.RemoveField(
            model_name='planificacao',
            name='professor',
        ),
    ]
