# Generated by Django 6.0.7 on 2026-08-13 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_initial'),
        ('professores', '0003_remove_professor_disciplinas'),
        ('tipos_ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ocorrencia', models.DateField()),
                ('descricao', models.TextField()),
                ('medida_tomada', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='alunos.aluno')),
                ('registada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_registadas', to='professores.professor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='tipos_ocorrencias.tipoocorrencia')),
            ],
            options={
                'verbose_name': 'Ocorrencia',
                'verbose_name_plural': 'Ocorrencias',
                'ordering': ['-data_ocorrencia', 'aluno'],
            },
        ),
    ]
