export const moduleLinks = [
  { path: '/professores', label: 'Professores', icon: 'bi-person-badge', color: 'green' },
  { path: '/disciplinas', label: 'Disciplinas', icon: 'bi-book', color: 'purple' },
  { path: '/turmas', label: 'Turmas', icon: 'bi-grid-3x3-gap', color: 'blue' },
  { path: '/alunos', label: 'Alunos', icon: 'bi-mortarboard', color: 'blue' },
  { path: '/leccionacoes', label: 'Leccionações', icon: 'bi-diagram-3', color: 'cyan' },
  { path: '/planificacoes', label: 'Planificações', icon: 'bi-journal-check', color: 'purple' },
  { path: '/controlo-aulas', label: 'Controlo de Aulas', icon: 'bi-calendar2-check', color: 'orange' },
  { path: '/pct', label: 'PCT', icon: 'bi-file-earmark-text', color: 'green' },
  { path: '/analise-pct', label: 'Análise PCT', icon: 'bi-graph-up-arrow', color: 'cyan' },
  { path: '/ocorrencias', label: 'Ocorrências', icon: 'bi-exclamation-triangle', color: 'red' },
  { path: '/tipos-ocorrencias', label: 'Tipos de Ocorrências', icon: 'bi-tags', color: 'yellow' },
  { path: '/reunioes', label: 'Reuniões', icon: 'bi-people', color: 'pink' },
  { path: '/relatorios', label: 'Relatórios', icon: 'bi-bar-chart-line', color: 'cyan' },
  { path: '/configuracoes', label: 'Configurações', icon: 'bi-gear', color: 'slate' },
];
