# Generated by Django 6.0.7 on 2026-08-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('assunto', models.CharField(max_length=180)),
                ('participantes', models.TextField(blank=True)),
                ('decisoes', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['-data', 'assunto'],
            },
        ),
    ]
