# Generated by Django 6.0.7 on 2026-08-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('professores', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecionacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecionacoes', to='turmas.turma'),
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='professores', to='disciplinas.disciplina'),
        ),
        migrations.AddField(
            model_name='lecionacao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecionacoes', to='professores.professor'),
        ),
        migrations.AddConstraint(
            model_name='lecionacao',
            constraint=models.UniqueConstraint(fields=('professor', 'disciplina', 'turma', 'ano_lectivo'), name='unique_lecionacao_professor_disciplina_turma_ano'),
        ),
    ]
