# Generated by Django 6.0.7 on 2026-08-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='disciplinas',
        ),
    ]
