# Generated by Django 6.0.7 on 2026-08-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=20)),
                ('sala', models.CharField(max_length=30)),
                ('periodo', models.CharField(choices=[('MANHA', 'Manha'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=20)),
                ('ano_lectivo', models.CharField(max_length=20)),
                ('turno', models.CharField(blank=True, max_length=30)),
                ('capacidade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diretor_turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_dirigidas', to='professores.professor')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['ano_lectivo', 'classe', 'sala', 'periodo'],
                'constraints': [models.UniqueConstraint(fields=('classe', 'sala', 'periodo', 'ano_lectivo'), name='unique_turma_classe_sala_periodo_ano')],
            },
        ),
    ]
