# Generated by Django 6.0.7 on 2026-08-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, unique=True)),
                ('categoria', models.CharField(choices=[('DISCIPLINAR', 'Disciplinar'), ('COMPORTAMENTAL', 'Comportamental'), ('ACADEMICA', 'Academica'), ('OUTROS', 'Outros')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Ocorrencia',
                'verbose_name_plural': 'Tipos de Ocorrencias',
                'ordering': ['categoria', 'descricao'],
            },
        ),
    ]
